// Generated by scripts/build-brand-assets.py from the fitted brand-mark
// geometry. Do not edit; re-run the script. app-logo-assets.test.ts pins
// this path to assets/brand/mark.svg so the in-app mark and the launcher
// icon stay one shape.
export const APP_LOGO_VIEWBOX_WIDTH = 741
export const APP_LOGO_VIEWBOX_HEIGHT = 704
export const APP_LOGO_PATH =
  'M 181 0 A 181 181 0 0 1 313.61 57.81 L 85.44 351.53 L 272.48 572.36 L 330.30 501.98 L 199.77 351.37 L 428.63 56.49 A 181 181 0 0 1 741.00 181.00 L 741 523 A 181 181 0 0 1 560.00 704.00 L 383.73 704.00 L 656.10 351.60 L 469.38 131.23 L 413.03 203.26 L 541.73 351.77 L 310.13 649.83 A 181 181 0 0 1 0.00 523.00 L 0 181 A 181 181 0 0 1 181.00 0.00 Z'
