/** Wrapped-prose reflow for the .md tab’s WebView editor, kept out of
 *  `-body-secondary.ts` only because that file is at its line ceiling. */
export const MOBILE_RICH_MARKDOWN_EDITOR_BODY_REFLOW = [
  '      // Fill wrapped prose to the screen. A single newline inside a paragraph',
  '      // is a SPACE in markdown, not a break; only two trailing spaces or an',
  '      // unescaped trailing backslash end a line. Painting every source newline',
  '      // as a <br /> is what made an 80-column document read as a ragged column',
  '      // on the phone (reported 2026-09-15 against this repo\\u2019s CLAUDE.md).',
  '      // Only an ODD run of trailing backslashes ends in an unescaped one, so a',
  "      // Windows path ending 'C:\\\\\\\\' is not a break.",
  '      function reflowLines(lines) {',
  "        var out = '';",
  '        for (var index = 0; index < lines.length; index += 1) {',
  "          var line = index > 0 ? String(lines[index] || '').replace(/^[ \\t]+/, '') : String(lines[index] || '');",
  '          if (index === lines.length - 1) {',
  "            out += line.replace(/[ \\t]+$/, '');",
  '            break;',
  '          }',
  '          var slashes = 0;',
  "          while (slashes < line.length && line.charAt(line.length - 1 - slashes) === '\\\\') {",
  '            slashes += 1;',
  '          }',
  '          if (slashes % 2 === 1) {',
  "            out += line.slice(0, -1) + '\\n';",
  '          } else if (/ {2,}$/.test(line)) {',
  "            out += line.replace(/[ \\t]+$/, '') + '\\n';",
  '          } else {',
  "            out += line.replace(/[ \\t]+$/, '') + ' ';",
  '          }',
  '        }',
  '        return out;',
  '      }',
].join('\n')
